chore(release): v3.7.1
Patch release that fixes the `HookOnProgress` PEP 604 / Python 3.9
import error introduced in 3.7.0, plus the action version bumps from
PR #56 (Node 24). v3.7.0 is being yanked in favor of this release
because importing the module on Python 3.9 raised:

    TypeError: unsupported operand type(s) for |: 'type' and 'NoneType'